# host : NCP socket : simulator line TCP port : fep-line.py flags
1:ncp01:4003:--no-init --send-break --max-simh-line 7
6:ncp06:6180:--no-init --select-first-line --max-simh-line 7
65:ncp65:16515:--no-init
